/* Re-download RATA's three typefaces from Google and rebuild public/fonts.

   Run this when a family, a weight or a subset changes — not on every build.
   The files are committed, because a build that reaches out to Google to
   produce a site whose point is not reaching out to Google has missed it.

     node scripts/vendor-fonts.mjs

   Google serves different CSS to different browsers, so the request carries a
   modern user agent: an older one gets .ttf instead of .woff2, which is roughly
   twice the bytes for the same glyphs.

   The unicode-range declarations are kept exactly as Google writes them. They
   are what makes vendoring every subset free — a browser downloads only the
   ranges the text on the page actually needs, so shipping hebrew costs nothing
   to a reader who never sees any. */
import { writeFile, mkdir, readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const DEST = join(HERE, '..', 'public', 'fonts');

/* The families and weights the pages actually ask for. Adding a weight here is
   the only supported way to start using one — a `font-weight: 800` that nothing
   has downloaded gets synthesised by the browser and looks wrong in a way
   nobody can quite name. */
const FAMILIES = [
  'Fredoka:wght@500;600;700',
  'Instrument+Sans:wght@400;500;600;700',
  'Sora:wght@400;600;700',
];

const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';
const OFL = { fredoka: 'fredoka', 'instrument-sans': 'instrumentsans', sora: 'sora' };

const HEADER = `/* RATA's three typefaces, served from this site rather than from Google.

   Vendored for one reason above the others: a request to fonts.googleapis.com
   tells Google every time somebody opens their mail. On a product whose whole
   claim is that your messages stay yours, that is the wrong first request to
   make on every page load — and on the desktop app it is a network call from a
   program that is supposed to work on a train.

   It is also faster. The Google stylesheet is render-blocking and resolves two
   extra hostnames before a single glyph arrives; this is one file from the
   origin the page already came from.

   Generated by scripts/vendor-fonts.mjs — do not edit. The unicode-range
   declarations are kept exactly as Google wrote them, so a browser still
   downloads only the subsets a page actually uses.

   All three families are SIL Open Font License 1.1; the licences are beside
   the files, in fonts/OFL-*.txt. */

`;

async function get(url, binary = false) {
  const r = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!r.ok) throw new Error(`${r.status} ${r.statusText} for ${url}`);
  return binary ? Buffer.from(await r.arrayBuffer()) : r.text();
}

await mkdir(DEST, { recursive: true });

const css = await get(
  `https://fonts.googleapis.com/css2?${FAMILIES.map(f => 'family=' + f).join('&')}&display=swap`
);

/* Each @font-face is preceded by a /* subset *\/ comment naming the range. */
const blocks = [...css.matchAll(/\/\* ([a-z0-9-]+) \*\/\s*(@font-face \{[\s\S]*?\})/g)];
if (!blocks.length) throw new Error('Google returned CSS in a shape this script does not understand');

const written = new Map();
const out = [];

for (const [, subset, block] of blocks) {
  const family = /font-family: '([^']+)'/.exec(block)[1];
  const weight = /font-weight: (\d+)/.exec(block)[1];
  const url = /url\((https:\/\/[^)]+)\)/.exec(block)[1];
  const slug = family.toLowerCase().replaceAll(' ', '-');
  const name = `${slug}-${weight}-${subset}.woff2`;

  if (!written.has(name)) {
    const bytes = await get(url, true);
    await writeFile(join(DEST, name), bytes);
    written.set(name, bytes.length);
  }
  out.push(block.replace(/url\(https:\/\/[^)]+\)/, `url(${name})`));
}

await writeFile(join(DEST, 'fonts.css'), HEADER + out.join('\n') + '\n');

/* The licences travel with the files. Vendoring an open font and leaving its
   licence behind is the one part of this that is not merely untidy. */
for (const [slug, dir] of Object.entries(OFL)) {
  const text = await get(`https://raw.githubusercontent.com/google/fonts/main/ofl/${dir}/OFL.txt`);
  if (!/SIL OPEN FONT LICENSE/i.test(text)) throw new Error(`${dir}: that does not look like an OFL`);
  await writeFile(join(DEST, `OFL-${dir}.txt`), text);
}

const total = [...written.values()].reduce((a, b) => a + b, 0);
console.log(`${written.size} files, ${(total / 1024).toFixed(0)} KB`);

/* A page that still points at Google has not been migrated, and the whole
   point is lost while one of them does. */
const pages = ['index.html', 'auth.html', 'app.html', 'account.html'];
for (const page of pages) {
  const html = await readFile(join(HERE, '..', 'public', page), 'utf8');
  if (/fonts\.(googleapis|gstatic)\.com/.test(html)) {
    console.error(`  WARNING: ${page} still loads fonts from Google`);
  }
}
