#!/usr/bin/env bash
# Assemble the desktop app's web assets from the one interface RATA has.
#
# There is deliberately no second copy of app.html in this repository. It is
# 250KB and two copies of it diverge within a month, with the desktop one being
# the copy nobody remembers to update. So it is taken from rata-next/public at
# build time, and the only differences are applied here, loudly.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
src="$here/../../rata-next/public"
out="$here/ui"

[ -d "$src" ] || { echo "no interface at $src" >&2; exit 1; }

rm -rf "$out"
mkdir -p "$out"
cp -r "$src/vendor" "$src/icons" "$out/"
cp "$src/manifest.json" "$out/"
cp "$here/ui-src/bridge.js" "$out/bridge.js"

# The desktop app IS the app: it opens straight into it rather than the
# marketing page, so app.html is what index.html means here.
cp "$src/app.html" "$out/index.html"

# The hook the bridge attaches to. If this ever disappears from app.html the
# desktop build must fail here rather than ship an app whose every action
# silently does nothing.
grep -q '__RATA_NATIVE__' "$out/index.html" || {
  echo "app.html has no __RATA_NATIVE__ hook in apiFetch — the desktop bridge has nothing to attach to" >&2
  exit 1
}

# Load the bridge before anything else runs.
grep -q '<script src="config.js"></script>' "$out/index.html" || {
  echo "app.html no longer loads config.js — the bridge injection point has moved" >&2
  exit 1
}
python3 - "$out/index.html" <<'PY'
import sys
p = sys.argv[1]
s = open(p, encoding='utf-8').read()
anchor = '<script src="config.js"></script>'
s = s.replace(anchor, anchor + '\n<script src="bridge.js"></script>', 1)

# Google Fonts, removed rather than allowed through the CSP.
#
# A local-first mail app that contacts Google on every launch tells Google when
# its customer opens their mail, which is the sort of thing this product exists
# not to do. The interface falls back to the system UI font until the three
# families are vendored — that is a visible difference and a known one.
import re
before = s
s = re.sub(r'\s*<link[^>]*fonts\.(googleapis|gstatic)\.com[^>]*>', '', s)
if s == before:
    print('note: no Google Fonts links found — either already vendored or moved', file=sys.stderr)
open(p, 'w', encoding='utf-8').write(s)
PY

# The device build has no Supabase and no server, which is exactly the state
# app.html already handles: it falls back to on-device accounts. The payment
# links still point at the website, because that is where buying happens.
cat > "$out/config.js" <<'JS'
/* Generated by sync-ui.sh — do not edit. The desktop build has no cloud
   backend by design; app.html already treats that as "device account". */
window.RATA_CONFIG = {
  supabaseUrl: '',
  supabaseKey: '',
  googleClientId: '',
  stripeBase: 'https://mailrata.org/#pricing',
  stripePro: 'https://mailrata.org/#pricing',
  stripePortal: 'https://mailrata.org/account',
  desktop: true,
};
JS

echo "ui/ assembled from rata-next/public ($(du -sh "$out" | cut -f1))"
