apiVersion: v1
kind: Service
metadata:
  name: audit-dlp
  namespace: center-point-inbox
  labels:
    app.kubernetes.io/name: audit-dlp
    app.kubernetes.io/part-of: center-point-inbox
    app.kubernetes.io/component: security
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: audit-dlp
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
