apiVersion: v1
kind: Service
metadata:
  name: google-provider
  namespace: center-point-inbox
  labels:
    app.kubernetes.io/name: google-provider
    app.kubernetes.io/part-of: center-point-inbox
    app.kubernetes.io/component: provider
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: google-provider
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
